server:
    port: 8080

spring:
    datasource:
        name: SYSDBA
        url: jdbc:dm://localhost:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        username: SYSDBA
        password: SYSDBA
        driver-class-name: dm.jdbc.driver.DmDriver
#        type: com.alibaba.druid.pool.DruidDataSource
#        druid:
#            initial-size: 5
#            min-idle: 5
#            max-active: 50
#            query-timeout: 10000
#            transaction-query-timeout: 6000
#            remove-abandoned-timeout: 30000
#            max-wait: 60000
#            time-between-eviction-runs-millis: 60000
#            min-victable-idle-time-millis: 300000
#            validation-query: select 1
#            test-while-idle: true
#            test-on-borrow: true
#            test-on-return: true
#            filters: stat,config,wall,log4j
#            connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJX6W1bmAays0eN2oAYDrdqYTvSPGWcU1+Bx5qF3TqIc6fOrc7+/7npOgHbqkCh+PrFbFxSUkvUXkCx6ZAaX/QcCAwEAAQ==
#            pool-prepared-statements: true
#            max-open-prepared-statements: 300
#            verify-server-certificate: false
#    servlet:
#      multipart:
#        max-file-size: 20MB
#        max-request-size: 200MB
#ribbon:
#    ConnectTimeout: 2000
#    ReadTimeout: 10000
#
mybatis:
    type-aliases-package: per.zs.studyDM
    mapper-locations: classpath:mapper/*.xml
    configLocation: classpath:mybatis-config.xml
#
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    pageSizeZero: true
#    params: count=countSql
#
#logging:
#    level:
#        com.changhong.classify: debug
        